# Script for posting test data to server.
# from sandbox
#curl -d "test_ipn=1&payment_type=instant&payment_date=08%3A39%3A48+Dec+01%2C+2011+PST&payment_status=Completed&payer_status=verified&first_name=John&last_name=Smith&payer_email=buyer%40paypalsandbox.com&payer_id=TESTBUYERID01&business=seller%40paypalsandbox.com&receiver_email=seller%40paypalsandbox.com&receiver_id=TESTSELLERID1&residence_country=US&item_name1=something&item_number1=AK-1234&quantity1=1&tax=2.02&mc_currency=USD&mc_fee=0.44&mc_gross=15.34&mc_gross" http://localhost:8080/

# production signup single payment
curl -d "protection_eligibility=Eligible&last_name=Bledsoe&txn_id=916697991F3054121&receiver_email=silencedefeat%40gmail.com&payment_status=Completed&payment_gross=1.34&tax=0.00&residence_country=US&option_name1=username&address_state=TN&payer_status=unverified&txn_type=web_accept&address_street=1760+Shipley+Rd%0D%0AApt+A&handling_amount=0.00&payment_date=12%3A47%3A44+Dec+01%2C+2011+PST&first_name=Sam&item_name=Shell+Account&address_country=United+States&charset=windows-1252&custom=&notify_version=3.4&address_name=Sam+Bledsoe&item_number=&receiver_id=5X6JG8DFQ57FC&option_selection1=testusera80&transaction_subject=Shell+Account&business=silencedefeat%40gmail.com&payer_id=Y9MH8FKLJ4REN&verify_sign=AvwtUHthdNaAcNY0AfWaEUe.MwW3AgZXAsmuFEk8Nh4ZOLSokWGr4-fA&address_zip=38501&payment_fee=0.34&address_country_code=US&address_city=Cookeville&address_status=confirmed&mc_fee=0.34&mc_currency=USD&shipping=0.00&payer_email=sam.bledsoe%40gmail.com&payment_type=instant&mc_gross=1.34&ipn_track_id=8kbp8Ywjsn-FuC429.367g&quantity=1" http://localhost:8080/

# production signup subscription - actually a payment, not the record i need
#curl -d "protection_eligibility=Ineligible&receiver_id=5X6JG8DFQ57FC&last_name=Bledsoe&txn_id=3H75400178600792E&business=silencedefeat%40gmail.com&receiver_email=silencedefeat%40gmail.com&payment_status=Completed&payment_gross=10.00&mc_fee=0.59&payer_id=Y9MH8FKLJ4REN&option_selection1=testuserballs&residence_country=US&option_name1=username&payer_status=unverified&txn_type=subscr_payment&verify_sign=AlN2ld9j915rqnBq5ghpVDr9Drx5Ae2mktmHypfNAIhMGjhOYmtZmwQe&subscr_id=I-KESMS9U1B7S6&payment_fee=0.59&payment_date=12%3A49%3A42+Dec+01%2C+2011+PST&first_name=Sam&item_name=Shell+Account&charset=windows-1252&mc_currency=USD&payer_email=sam.bledsoe%40gmail.com&notify_version=3.4&payment_type=instant&transaction_subject=Shell+Account&mc_gross=10.00&ipn_track_id=3miwwXue5ypKQa7UQZNhRw" http://localhost:8080/

